config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  root 'main#index'

  # devise
  devise_for :users
  resources :users, only: [:show]
  resources :categories
  resources :recipes do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
  end


  # user
  get '/users/:id', to: 'users#show', as: 'user_profile'
  get '/users/:id/recipes', to: 'users#recipes', as: 'user_profile_recipes'

  # private pages
  get 'myrecipes', to: 'users#my_recipes', as: 'my_recipes'
  get 'favorites', to: 'users#favorites', as: 'favorites'
  
  # search
  get '/search', to: 'search#search', as: 'search'

  # videos
  get "/videos/:id", to: "videos#show", as: "video"
  get '/cookbook', to: "main#cookbook", as: "cookbook"
  # admin panel
  namespace :admin do
    root 'dashboard#index'
    resources :users
    resources :categories
    resources :recipes do
      member do
        post :publish
      end
    end
    resources :comments do
      member do
        post :publish
      end
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :recipe
    belongs_to :user

    scope :moderated, -> { joins(:user).where(users: { comment_moderation: true }) }
    scope :unmoderated, -> { joins(:user).where(users: { comment_moderation: false }) }
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < AdminController
    before_action :set_comment, only: [:show, :edit, :update, :destroy]

    def index
        @comments = Comment.all
        if params[:type] && params[:type] == 'unmoderated'
            @comments = Comment.unmoderated
        end
    end

    def show
    end

    def new
        @comment = Comment.new
    end

    def edit

    end

    def update
        if @comment.update(comment_params)
            redirect_to [:admin, @comment], notice: 'Комент успішно відредагований'
        else
            render :edit
        end
    end

    def destroy
        @comment.destroy
        redirect_to admin_comments_url, notice: 'Комент видалений'
    end
    
    def publish
        @comment = Comment.find(params[:id])
        @comment.user.update(comment_moderation: true)
        redirect_to admin_comments_path, notice: 'Коментарі користувача опубліковані'
    end

    private

    def set_comment
        @comment = Comment.friendly.find(params[:id])
    end

    def comment_params
        params.require(:comment).permit(:body, :image)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
      @recipe = Recipe.friendly.find(params[:recipe_id])
      @comment = @recipe.comments.new(comment_params)
      @comment.user = current_user
  
      if @comment.save
        redirect_to @recipe, notice: 'Комментар успішно додано.'
      else
        render 'recipes/show'
      end
    end
  
    private
  
    def comment_params
      params.require(:comment).permit(:body, :image)
    end
end

app/views/admin/comments/index.html.erb
<h1>Коментарі</h1>

<a href="/admin/comments" class="btn btn-primary">
  Опубліковані <span class="badge badge-light"> <%= Comment.moderated.count %> </span>
</a>

<a href="/admin/comments?type=unmoderated" class="btn btn-primary">
  На модерації <span class="badge badge-light"> <%= Comment.unmoderated.count %></span>
</a>

<br><br>

<table class="table">
  <thead>
    <tr>
      <th>Фото</th>
      <th>Коментар</th>
      <th>Дата</th>
      <th>Дії</th>
    </tr>
  </thead>
  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><img src="<%= comment.image.url %>" style="width: 100px;"/></td>
        <td><%= comment.body %></td>
        <td><%= comment.created_at %></td>
        <td>
          <% if comment.user.comment_moderation == false %>
            <%= link_to 'Опублікувати', publish_admin_comment_path(comment), method: :post, class: 'btn btn-success' %>
          <% end %>
          <%= link_to 'Редагувати', edit_admin_comment_path(comment), class: 'btn btn-warning' %>
          <%= link_to 'Видалити', admin_comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>