config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  root 'main#index'

  # devise
  devise_for :users
  resources :users, only: [:show]
  resources :categories
  resources :recipes do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
  end


  # user
  get '/users/:id', to: 'users#show', as: 'user_profile'
  get '/users/:id/recipes', to: 'users#recipes', as: 'user_profile_recipes'

  # private pages
  get 'myrecipes', to: 'users#my_recipes', as: 'my_recipes'
  get 'favorites', to: 'users#favorites', as: 'favorites'
  
  # search
  get '/search', to: 'search#search', as: 'search'

  # videos
  get "/videos/:id", to: "videos#show", as: "video"
  get '/cookbook', to: "main#cookbook", as: "cookbook"
  # admin panel
  namespace :admin do
    root 'dashboard#index'
    resources :users
    resources :categories
    resources :recipes do
      member do
        post :publish
      end
    end
    resources :comments do
      member do
        post :publish
      end
    end
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    extend FriendlyId
    friendly_id :title, use: :slugged

    belongs_to :category
    belongs_to :user
    has_many :recipe_steps
    has_many :comments
    has_many :likes

    accepts_nested_attributes_for :recipe_steps, reject_if: :all_blank, allow_destroy: true

    # enum status: [:draft, :moderation, :published]
    mount_uploader :image, ImageUploader
    enum status: [:draft, :moderation, :published]

    has_many :favorites

    # scope moderated, where users in association recipe_moderation is true
    scope :moderated, -> { joins(:user).where(users: { recipe_moderation: true }) }
    scope :unmoderated, -> { joins(:user).where(users: { recipe_moderation: false }) }
    
    def normalize_friendly_id(input)
        input.to_slug.transliterate(:ukrainian).normalize.to_s
    end

    def likes_count
        likes.where(like_type: 'like').count
    end
    
    def dislikes_count
        likes.where(like_type: 'dislike').count
    end
end

app/controllers/admin/recipes_controller.rb
class Admin::RecipesController < AdminController
    before_action :set_recipe, only: [:show, :edit, :update, :destroy]

    def index
        @recipes = Recipe.moderated
        if params[:type] && params[:type] == 'unmoderated'
            @recipes = Recipe.unmoderated
        end
    end

    def show
    end

    def new
        @recipe = Recipe.new
    end

    def edit
        @recipe = Recipe.friendly.find(params[:id])
        @categories = Category.all
    end

    def create
        @recipe = Recipe.new(recipe_params)

        if @recipe.save
            redirect_to [:admin, @recipe], notice: 'Рецепт успішно створений'
        else
            render :new
        end
    end
    
    def publish
        @recipe = Recipe.friendly.find(params[:id])
        @recipe.user.update(recipe_moderation: true)
        redirect_to admin_recipes_path, notice: 'Рецепт опублікований'
    end

    def update
        if @recipe.update(recipe_params)
            redirect_to admin_recipes_path, notice: 'Рецепт успішно відредагований'
        else
            render :edit
        end
    end

    def destroy
        @recipe.destroy
        redirect_to admin_recipes_url, notice: 'Рецепт видалений'
    end

    private

    def set_recipe
        @recipe = Recipe.friendly.find(params[:id])
    end

    def recipe_params
        params.require(:recipe).permit(:title, :image, :description, :ingredients, :status, :category_id, :slug, recipe_steps_attributes: [:description, :position, :image])
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    add_breadcrumb "Рецепти", :root_path

    def index
        @recipes = Recipe.moderated.order(created_at: :desc)
    end

    def new
        @categories = Category.all
        @recipe = Recipe.new

        add_breadcrumb "Новий рецепт", new_recipe_path
    end

    def create
        @recipe = Recipe.new(recipe_params)
        @recipe.user_id = current_user.id
        if @recipe.save
            flash[:success] = "Рецепт успішно створено!"
            redirect_to @recipe
        else
            error_message = @recipe.errors.full_messages.join(", ")
            flash[:error] = error_message
            render 'new'
        end
    end

    def show
        @recipe = Recipe.friendly.find(params[:id])
        if current_user && @recipe.user == current_user

        elsif @recipe.user.recipe_moderation == false
            return redirect_to root_path, alert: "Користувач на модерації"
        end

        add_breadcrumb "#{@recipe.title}", recipe_path
    end

    def edit
        @recipe = Recipe.find(params[:id])
        @categories = Category.all
    end

    def update
        @recipe = Recipe.find(params[:id])
        if @recipe.update(recipe_params)
            flash[:success] = "Рецепт успішно оновлено!"
            redirect_to @recipe
        else
            error_message = @recipe.errors.full_messages.join(",")
            flash[:error] = error_message
            redirect_to edit_recipe_path(@recipe)
        end
    end

    def destroy

    end

    private

    def recipe_params
        params.require(:recipe).permit(:title, :description, :ingredients, :image, :category_id, :user_id, recipe_steps_attributes: [:description, :position, :image])
    end
end

app/helpers/recipes_helper.rb
# В вашем helper-файле
module RecipesHelper
    def link_to_add_fields(name, f, association)
      new_object = f.object.send(association).new
      id = new_object.object_id
      fields = f.fields_for(association, new_object, child_index: id) do |ingredient_fields|
        render(association.to_s.singularize + "_fields", f: ingredient_fields)
      end
      link_to(name, '#', class: 'add_fields', data: { id: id, fields: fields.gsub("\n", "") })
    end
end
  

app/views/admin/recipes/_recipe_step_fields.html.erb
<div class="nested-fields">
    <%= f.hidden_field :position, value: 1.to_s %>
    <div style="display: flex; flex-direction: row; width: 100%;">
      <%= f.text_area :description, class: "form-control" %>
      <div class="recipe-step-photo">
          <%= f.label "Фото" %><br>
          <%= f.file_field :image %>
      </div>
      <%= link_to_remove_association "X", f, class: "btn btn-default" %>
    </div>
</div>

app/views/admin/recipes/edit.html.erb
<h1>
    Редагування рецепту
</h1>

<div class="steps-block mt-15">
    <%= form_for @recipe, :url => { :action => "update" } do |f| %>
        <p>
            <%= f.label :title, "Назва рецепту" %><br>
            <%= f.text_field :title, class: "form-control" %>
        </p>

        <p>
            <%= f.label :image, "Фото рецепта" %><br>
            <%= f.file_field :image %>
        </p>

        <p>
            <%= f.label :ingredients, "Інгредієнти (кожен на новій строчці)" %><br>
            <%= f.text_area :ingredients, class: "form-control" %>
        </p>

        <p>
            <%= f.label :description, "Короткий опис рецепту" %><br>
            <%= f.text_area :description, class: "form-control" %>
        </p>

        <p>
            <%= f.label :category_id, "Виберіть категорію" %><br>
            <%= f.select :category_id, options_for_select(@categories.map { |c| [c.title, c.id] }, @recipe.category_id), { } , class: "form-control"  %>
        </p>

        <p>
            <%= f.label :recipe_steps, "Шаги рецепту" %><br>
            <%= f.fields_for :recipe_steps do |step_form| %>
                <%= render 'recipes/recipe_step_fields', f: step_form %>
            <% end %>
        </p>
        
        
        <div class="actions" data-step-index="0">
            <%= link_to_add_association "Додати шаг", f, :recipe_steps, class: 'btn btn-primary' %>
        </div>

        <p>
            Шагі
        </p>
        
        <%= f.submit "Редагувати рецепт", class: "btn btn-primary" %>
        </p>
    <% end %>
</div>

app/views/admin/recipes/index.html.erb
<h1>Рецепти</h1>

<a href="/admin/recipes" class="btn btn-primary">
  Рецепти <span class="badge badge-light"> <%= Recipe.moderated.count %> </span>
</a>

<a href="/admin/recipes?type=unmoderated" class="btn btn-primary">
  Модерація <span class="badge badge-light"> <%= Recipe.unmoderated.count %></span>
</a>

<br><br>

<table class="table">
  <thead>
    <tr>
      <th>Фото</th>
      <th>Назва</th>
      <th>Опис</th>
      <th>Дата</th>
      <th>Користувач</th>
      <th>Дії</th>
    </tr>
  </thead>
  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td>
          <% if recipe.image.url %>
            <%= image_tag recipe.image.url, width: '90px' %>
          <% end %>
        </td>
        <td><%= recipe.title %></td>
        <td style="width: 60%;"><%= recipe.description %></td>
        <td><%= recipe.created_at %></td>
        <td><a href="/users/<%= recipe.user.username %>"><%= recipe.user.username %></a></td>
        <td>
          <!-- button for publuish recipe and allow user to publish recipes -->
          <% if recipe.user.recipe_moderation == false %>
            <%= link_to 'Опублікувати', publish_admin_recipe_path(recipe), method: :post, class: 'btn btn-success' %>
          <% end %>
          <%= link_to 'Редагувати', edit_admin_recipe_path(recipe), class: 'btn btn-warning' %>
          <%= link_to 'Видалити', admin_recipe_path(recipe), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>