config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  root 'main#index'

  # devise
  devise_for :users
  resources :users, only: [:show]
  resources :categories
  resources :recipes do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
  end


  # user
  get '/users/:id', to: 'users#show', as: 'user_profile'
  get '/users/:id/recipes', to: 'users#recipes', as: 'user_profile_recipes'

  # private pages
  get 'myrecipes', to: 'users#my_recipes', as: 'my_recipes'
  get 'favorites', to: 'users#favorites', as: 'favorites'
  
  # search
  get '/search', to: 'search#search', as: 'search'

  # videos
  get "/videos/:id", to: "videos#show", as: "video"
  get '/cookbook', to: "main#cookbook", as: "cookbook"
  # admin panel
  namespace :admin do
    root 'dashboard#index'
    resources :users
    resources :categories
    resources :recipes do
      member do
        post :publish
      end
    end
    resources :comments do
      member do
        post :publish
      end
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :subcategories, class_name: 'Category', foreign_key: 'parent_id'
    belongs_to :parent, class_name: 'Category', optional: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
    before_action :set_category, only: [:show, :edit, :update, :destroy]

    def index
        @categories = Category.all
    end

    def show
    end

    def new
        @category = Category.new
    end

    def edit
    end

    def create
        @category = Category.new(category_params)

        if @category.save
            redirect_to [:admin, @category], notice: 'Категорія успішно создана'
        else
            render :new
        end
    end

    def update
        if @category.update(category_params)
            redirect_to [:admin, @category], notice: 'Категорія успішно відредагована'
        else
            render :edit
        end
    end

    def destroy
        @category.destroy
        redirect_to admin_categories_url, notice: 'Категорія видалена'
    end

    private

    def set_category
        @category = Category.find(params[:id])
    end

    def category_params
        params.require(:category).permit(:title, :image, :description, :parent_id)
    end
    
end

app/views/admin/categories/_form.html.erb
<%= form_with(model: [:admin, category], local: true) do |form| %>
  <div class="form-group">
    <%= form.label "Назва" %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label "Опис" %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label "Фото" %>
    <%= form.file_field :image, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label "Батьківська категорія" %>
    <%= form.collection_select :parent_id, Category.all, :id, :title, { include_blank: true }, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit "Зберегти", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Редагування категорії</h1>

<%= render 'form', category: @category %>


<%= link_to 'Назад', admin_categories_path, class: 'btn btn-primary' %>

app/views/admin/categories/index.html.erb
<h1>Категорії</h1>

<table class="table">
  <thead>
    <tr>
      <th>Назва</th>
      <th>Опис</th>
      <th>Дата</th>
      <th>Дії</th>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= category.description %></td>
        <td><%= category.created_at %></td>
        <td>
          <%= link_to 'Редагування', edit_admin_category_path(category), class: 'btn btn-warning' %>
          <%= link_to 'Видалити', admin_category_path(category), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to '+ Нова категорія', new_admin_category_path, class: 'btn btn-success' %>

app/views/admin/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Назад', admin_categories_path, class: 'btn btn-primary' %>

app/views/admin/categories/show.html.erb
<h1><%= @category.title %></h1>

<p><strong>Title:</strong> <%= @category.title %></p>
<p><strong>Description:</strong> <%= @category.description %></p>

<%= link_to 'Edit', edit_admin_category_path(@category), class: 'btn btn-warning' %>
<%= link_to 'Back', admin_categories_path, class: 'btn btn-primary' %>