config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  root 'main#index'

  # devise
  devise_for :users
  resources :users, only: [:show]
  resources :categories
  resources :recipes do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
  end


  # user
  get '/users/:id', to: 'users#show', as: 'user_profile'
  get '/users/:id/recipes', to: 'users#recipes', as: 'user_profile_recipes'

  # private pages
  get 'myrecipes', to: 'users#my_recipes', as: 'my_recipes'
  get 'favorites', to: 'users#favorites', as: 'favorites'
  
  # search
  get '/search', to: 'search#search', as: 'search'

  # videos
  get "/videos/:id", to: "videos#show", as: "video"
  get '/cookbook', to: "main#cookbook", as: "cookbook"
  # admin panel
  namespace :admin do
    root 'dashboard#index'
    resources :users
    resources :categories
    resources :recipes do
      member do
        post :publish
      end
    end
    resources :comments do
      member do
        post :publish
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # enum role 0 - user, 1 admin
  enum role: [:user, :admin]
  # enum status 0 - active, 1 - banned
  enum status: [:active, :banned]
  
  mount_uploader :avatar, AvatarUploader
  has_many :recipes, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  validates :username, presence: true

  has_many :likes
  has_many :favorites
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
    def index
        @users = User.all
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    add_breadcrumb "Рецепти", :root_path

    def recipes
        @user = User.find(params[:id])
    end
    
    def favorites
        @user = current_user
        @favorite_recipes = @user.favorites.map(&:recipe)
    end

    def show
        @user = User.find_by(username: params[:id])
        add_breadcrumb "#{@user.username}", user_profile_path
    end
end

app/views/admin/users/index.html.erb
 <h1>Користувачі</h1>

 <table class="table">
    <thead>
      <tr>
         <th>Username</th>
         <th>Електронна пошта</th>
         <th>Дата реєстрації</th>
         <th>Дії</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
         <tr>
            <td><%= user.username %></td>
            <td><%= user.email %></td>
            <td><%= user.created_at %></td>
            <td>
              <% if user.admin? %>
              <% else %>
              <%= link_to 'Видалити', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
              <% end %>
            </td>
         </tr>
      <% end %>
    </tbody>
 </table>